[package]
name = "rust-playground"
version = "0.1.0"
edition = "2021"
authors = ["Emin <example@example.com>"]
description = """
A simple playground for rust
"""

[dependencies]
log = "0.4"
pretty_env_logger = "0.5"
